### ISSUE TITLE
just a suggestion

### ISSUE THREAD

**Issue by besm-paul** [ms609/Ternary#10]
Hi
I have few things I would like to see in this ternary plot.

1. It would be better to have at least 100 lines from 0 to 100. The numbering is fine with step size of 10.

1. I saw your example of three things at edges A,B and C. What if I take a small part from the plot?
 If I want to magnify a small triangle within it to the whole size. Just magnifying the page is not what I am looking for.
        Lets say, I want the ternary plot of A.25B.25C.5 (one edge); B.25C.75 (another edge) and B.5C.5 (the third edge). This is not a point in the plot. How can you make a triangle with these three corners?

Regards
Besm Paul

**Comment by ms609** [comment]
Thanks for the suggestions.  I'll take a look soon and see whether I can make these possible.

**Comment by ms609** [comment]
I've added a new option to control minor grid lines, and updated the documentation to make it a little clearer how one might zoom in and crop to a particular region of the ternary plot.  This will appear on CRAN soon.  Hope that helps; do please let me know if you have any further suggestions!
