### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by chrarnold** [ms609/Ternary#13]
Hi,

thanks for the package, I was able to very quickly get a ternary plot. However, I am having overlapping labels, and I am wondering if there is already a way to avoid that, such as mimicking a ggrepel approach to avoid overlapping labels or something?

I have 187 points in my data, and although I only want to label those appearing in corners, they are still overlapping, so how to best avoid that?

Thanks!

**Comment by ms609** [comment]
Hi, glad you are finding the package useful, and thanks for the suggestion.  Are you able to post an image of your plot so I can get a clearer idea of the problem, and think about how I might implement an appropriate solution?

**Comment by ms609** [comment]
Hi, glad you are finding the package useful, and thanks for the suggestion.  Are you able to post an image of your plot so I can get a clearer idea of the problem, and think about how I might implement an appropriate solution?

**Comment by ms609** [comment]
I've closed this issue for now as I can't quite get a clear picture of what you are aiming to accomplish. If you're able to provide more details, please feel free to re-open this issue and I'll work on a solution.
