### ISSUE TITLE
I have a suggestion!

### ISSUE THREAD

**Issue by jfearon4** [ms609/Ternary#25]
Thanks for Ternary.  Can you think of a good way to use existing functions in the package to render lines into arrows (ie add an arrow head onto line)?

**Comment by ms609** [comment]
Thanks for your suggestion.  I've actually wanted to do something similar myself; my clumsy solution was to make an arrowhead by drawing two more short lines at the tip.  It sounds like it might be worth me adding something a little more sophisticated into the package...

**Comment by ms609** [comment]
[v1.1.1](https://github.com/ms609/Ternary/commit/5c571a102223ea9c83686eeefa06ae763150f3b8) now includes a function `TernaryArrows` providing an interface to the `arrows` function in the `graphics` package.
The new version's on its way to CRAN now and should appear in the next few days; meanwhile, use
`devtools::install_github('ms609/Ternary')` to install.

**Comment by jfearon4** [comment]
Thanks, that’s great.
