### ISSUE TITLE
Allow a, b, and c to sum to something other than 100 

### ISSUE THREAD

**Issue by johntwhelan** [ms609/Ternary#33]
It seems like the library only allows plots with a+b+c=100.  It would be useful to be able to specify a different value for the sum, e.g., to let a+b+c=1.

**Comment by ms609** [comment]
Can you use the `axis.labels` parameter to achieve this effect?
Try for example
`TernaryPlot(axis.labels=seq(0, 1, by = 0.1))`

If this provides the desired outcome, I'll add it as an example to the vignette.

**Comment by johntwhelan** [comment]
Yes, I think that has the desired effect.  I was worried about plotting data that summed to 1 rather than 100, but since it's all re-scaled for plotting, it doesn't matter.  (I seem to recall ggtern does the same thing, now that I think about it.)

Thanks for the quick reply!
