### ISSUE TITLE
[QUESTION] axis numbers rotation

### ISSUE THREAD

**Issue by coen22** [ms609/Ternary#38]
First of all, thank you for this very nice package!

is it possible to leave all axis numbers unrotated? (Just like all other text on screen)

**Comment by ms609** [comment]
Glad you are finding the package useful!  I've added some new parameters that should allow you to customise the axis rotation as you choose.  Install the latest version of the package with `devtools::install_github('ms609/Ternary')` and let me know how you get on!

**Comment by coen22** [comment]
You're fast :) I've tried it and it works
Thank you so much for your fast response!
