### ISSUE TITLE
Suggestion: color mixing in rgb()

### ISSUE THREAD

**Issue by UK85** [ms609/Ternary#40]
Hi Martin,
is it possible to define a function for TernaryPointValues() such that there are three predefined colors at the corners and that they mix towards the center (when putting TernaryPointValues(rgb) it works but I would like to use different colors than red, green, blue)?

Best wishes
Uli

**Comment by ms609** [comment]
Hi Uli,

Yes, it's certainly possible; there are a variety of approaches you might take, some of which are mentioned in [this stackoverflow post](https://stackoverflow.com/questions/13200751).

One way to start would be to build a function based on [`mixcolor()`](https://www.rdocumentation.org/packages/colorspace/versions/1.4-1/topics/mixcolor): would the following work?  (replace `colorX` with your desired colors.)

```r
function colormixer(a, b, c) {
   firstMix = mixcolor(a/(a + b), color1, color2)
   finalMix = mixcolor((a + b) / (a + b + c), firstMix, color3)
}
```

**Comment by ms609** [comment]
I got enthusiastic and started looking at how one might build a perceptually uniform 3-way colour mixing function; I couldn't find one available, but found a couple of promising links:

https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/convertColor.html
-> http://www.brucelindbloom.com/
https://mathematica.stackexchange.com/questions/7483/

I might follow up on this when I have more time...

**Comment by UK85** [comment]
Hi Martin,
good to now that this is not a trivial problem and I am happy that I inspired you digging into this.

Following your suggestion I tried:

```
colormixer <- function (a, b, c) {
   firstMix = mixcolor(a/(a + b), RGB(0,0,1), RGB(1,0,0))
   finalMix = mixcolor((a + b) / (a + b + c), firstMix, RGB(0,1,0))
   x <- c(finalMix)
   return(x[1])
}

cols <- `TernaryPointValues(Func=colormixer)
```

Unfortunately, it does not work, the TernaryPointValues() function does not fill the "z". Any idea how I could fix this?

Best wishes
Uli

**Comment by ms609** [comment]
Here's a complete working example.  (I also fixed a maths error in the original code.)

```r
library("colorspace")

ColorMixer <- function (a, b, c) {
  firstMix <- mixcolor(a / (a + b), RGB(1, 0.5, 0), RGB(0.5, 0, 1))
  finalMix <- mixcolor(c / (a + b + c), firstMix, RGB(0, 1, 0.5))
  apply(attr(finalMix, 'coords'), 1, function (x) rgb(x[1], x[2], x[3]))
}

TernaryPlot()
cols <- TernaryPointValues(ColorMixer)
ColourTernary(cols, spectrum = NULL)
```

**Comment by UK85** [comment]
Great!
Many thanks and best wishes,
Uli
