### ISSUE TITLE
Suggestion: I like your package! I wonder if it is possible to reproduce a graph with Holdridge life zones?

### ISSUE THREAD

**Issue by jamestsakalos** [ms609/Ternary#48]

**Comment by ms609** [comment]
Hi, thanks for the suggestion; this should be possible in principle, but I would probably need to extend the package a little.  To do so most effectively, it would be useful to have a handle on the sort of data that you would be plotting: are you able to share an example dataset, perhaps by attaching to a comment as a zipped `.Rda`, or by pasting the output of `dput(myExampleData)`?
