### ISSUE TITLE
Is it possible to draw gridlines on top of my background color?

### ISSUE THREAD

**Issue by victorkorir1** [ms609/Ternary#54]
This is my implementation.I get a plot that is almost exactly what I want but I would like to have my grid-lines visible on top of the background color.
`
TernaryPlot(alab="% Bustime \u2192", blab="% Tramtime \u2192", clab="\u2190 % Traintime ",
            lab.col=c('red', 'green3', 'blue'),
            point='up', lab.cex=1.5, grid.minor.lines=1, axis.cex=0.8,
            grid.lty='solid', col=rgb(0.9, 0.9, 0.9), grid.col='white', 
            axis.col=rgb(0.6, 0.6, 0.6), ticks.col=rgb(0.6, 0.6, 0.6),
            padding=0.08
cols <- TernaryPointValues(rgbWhite)
ColourTernary(cols, spectrum = NULL, resolution=45)
`
This is my result:
![image](https://user-images.githubusercontent.com/25318422/146919324-cbf29c40-4aef-4c65-b761-513c3a1e45ae.png)

However I would like to have a visualization like this one but probably make the grids black

![image](https://user-images.githubusercontent.com/25318422/146919398-4f0af63b-6c57-4c05-a72c-46aac475e7b2.png)

**Comment by ms609** [comment]
Good question! I'll have to think a little about the best way to do this.   Meanwhile, a workaround would be to set the fill colour to be semi-transparent.

**Comment by victorkorir1** [comment]
Thanks for the swift feedback,how can I set the background color to be semi-transparent?

**Comment by ms609** [comment]
Try setting the alpha parameter in `rgb` to, for example, 128 (see https://ms609.github.io/Ternary/articles/Ternary.html), or specifying colours in RGBA format, e.g. `"#ff0000cc"`
