### ISSUE TITLE
Interactivity (Ternary plot)

### ISSUE THREAD

**Issue by valedeceras** [ms609/Ternary#63]
Hi, first of all thank you for your very usefull package.

I want to include a ternary plot in a shiny app with mouse actions, so that I can get info on any observation clicked.

It's quite simple with cartesian coordinates using shiny::plotOutput mouse events. In a ternary space not quite.

In the following reproducible example I'm using Ternary::TernaryCoords to convert xyz coordinates to cartesian values. I'm not quite sure it the correct path of action.

At the moment I get the error: "Parameter `abc` must be a vector of length three".

The fact that there is not much information on the output structure of the click event also doesn't help.

Any ideas on how to implement interactivity to the ternary plots?

Thank you

```
library(shiny)
library(Ternary)

dd <- data.frame(x=c(6), y=c(2), z=c(2))

ui <- fluidPage(
  plotOutput("plot", click = "plot_click"),
  verbatimTextOutput("d")
)
server <- function(input, output, session) {
  output$plot <- renderPlot({
    TernaryPlot(axis.labels = F, axis.tick = F, grid.lines = 0, grid.minor.lines = 0)
    AddToTernary(points, coordinates = dd)
  })
  output$d <- renderPrint({   
    req(input$plot_click)
    xx <- (TernaryCoords(c(input$plot_click$x,input$plot_click$y,input$plot_click$z)))
    print(xx)
  })
}
shinyApp(ui, server)
```

**Comment by ms609** [comment]
`input$plot_click` returns the cartesian coordinates that are clicked, so `input$plot_click$z` is not defined.  Try `XYToTernary()`:

```r
library("shiny")
library("Ternary")

ui <- fluidPage(
  plotOutput("plot", click = "plot_click"),
  verbatimTextOutput("d")
)
server <- function(input, output, session) {
  
  dd <- data.frame(x=c(6), y=c(2), z=c(2))
  output$plot <- renderPlot({
    TernaryPlot(axis.labels = F, axis.tick = F, grid.lines = 0, grid.minor.lines = 0)
    AddToTernary(points, coordinates = dd)
  })
  output$d <- renderPrint({   
    req(input$plot_click)
    xx <- (XYToTernary(input$plot_click$x,input$plot_click$y))
    xx
  })
}
shinyApp(ui, server)

```

**Comment by valedeceras** [comment]
Yes, it makes sense. I was thinking the wrong way around.
Thank you very much for the quick response.

**Comment by ms609** [comment]
Great, glad to be able to help!
