### ISSUE TITLE
Feature request: Colorbar

### ISSUE THREAD

**Issue by mnlang** [ms609/Ternary#66]
Hi Martin

I am trying to create a colorbar for a "ColourTernary" plot.  I don't think this is currently supported, is it? If not, it would be great to have that feature or I could also create one in R myself, however, I don't really know the exact breaks you are using in the  "ColourTernary" plot.

For reference, see also this [stackoverflow](https://stackoverflow.com/questions/59685973/ternary-plot-in-r-with-color-map) question with a request for a colorbar (not by me). 

Would be great to hear from you and thanks for the nice package!
Best, Moritz

**Comment by ms609** [comment]
Hi Moritz, thanks for the question, this shouldn't be too difficult to implement, I'll have a think about the best approach and get back to you once I have the opportunity, hopefully in the next couple of weeks.

Martin

**Comment by mnlang** [comment]
Hi Martin

This sounds great - thanks a lot and please keep me updated! In case it's too much work, an e.g., invisible return of the exact breaks used would be already very helpful!

All the best, 
Moritz

**Comment by ms609** [comment]
I've posted an [SO answer](https://stackoverflow.com/questions/59685973) and added an example to the vignettes (see [§Contours](https://ms609.github.io/Ternary/dev/articles/Ternary.html#contours)).  

Before the next release I indend to:
- [ ] add a native implementation (avoiding a TreeTools dependency) with a sensible default position (cf. #68 )
- [ ] Add an example to the [interpolation vignette](https://ms609.github.io/Ternary/articles/interpolation.html)

**Comment by ms609** [comment]
Having put a bit of time into developing a solution here (spawning the "PlotTools" package, coming soon to CRAN) I have attempted a native implementation in `ColourTernary()`, available in v2.1.3.9003 and coming soon to CRAN.  
Documentation will appear at https://ms609.github.io/Ternary/dev/reference/ColourTernary.html in the next couple of days.
