### ISSUE TITLE
Suggestion: colour filled contours

### ISSUE THREAD

**Issue by jemmings-git** [ms609/Ternary#69]
This is a great little package - thank you!

Is it possible to add a colour fill bounded by the density contours in the function TernaryDensityContour() ?

i.e., in order to produce more smooth colour output compared to the tile fill ColourTernary()

**Comment by ms609** [comment]
Interesting idea, thanks – I'll investigate!

**Comment by ms609** [comment]
Implemented – let me know how you get on, or whether you see any issues with the implementation.  

To install, use
```r
remotes::install_github("ms609/Ternary")
```
