### ISSUE TITLE
Is there a way to align the tip labels with the tip?

### ISSUE THREAD

**Issue by michaelschwob** [ms609/Ternary#85]
At the moment, I have the following ternary plot using 
```
TernaryPlot(atip = expression(u[1]), btip = expression(u[2]), ctip = expression(u[3]), col = "lightblue", grid.lines = 2, grid.col = "black", grid.lty = 2, axis.tick = FALSE, axis.labels = FALSE)
AddToTernary(graphics::points, dirData, pch = 16, col = "red")
```
![image](https://github.com/ms609/Ternary/assets/13207676/a2ef02dc-46a3-4640-b117-b0d3b0a38617)

Is there a simple way that I can align the tip labels (u_1,u_2,u_3) to the center of the tip? I have not found the right argument to do such a thing (yet).

**Comment by ms609** [comment]
To create a label right at the tip, you could use 
 
```r
TernaryText(c(1, 0, 0), "U1", pos = 3, offset = 1)
```
![image](https://github.com/ms609/Ternary/assets/1695515/efadfe1b-d4c0-4edf-b5b1-ce3f3df85176)

or

```r
TernaryText(c(1, 0, 0), "  U1"), srt = 90, pos = 4, offset = 0)
```
![image](https://github.com/ms609/Ternary/assets/1695515/0c38faba-95c7-49de-9903-b6ea04870899)


This is admittedly a bit fiddly, particularly for the other two corners.  The challenge in automating this is in ensuring that the tip labels don't overlap any axis labels.  But it should be possible to come up with something. I'll have a think and see whether I can come up with an easier solution over the next couple of weeks.

**Comment by michaelschwob** [comment]
Thank you for the quick fix, Martin! I appreciate it :)
